#!/usr/bin/env bash

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

install_asdf_plugin() {
  local name="$1"
  local url="$2"

  if ! asdf plugin-list | grep -Fq "$name"; then
    asdf plugin add "$name" "$url"
  fi
}

install_asdf_language() {
  local language="$1"
  local version="$2"
  asdf install "$language" "$version"
  asdf global "$language" "$version"
}

DEFAULT_NODEJS_VERSION="16.13.0"
DEFAULT_PYTHON_VERSION="3.10.0"
ZSH_CUSTOM="${ZSH_CUSTOM:=$HOME/.oh-my-zsh/custom}"

printf "\\nWhich version of Node.js would you like to install?
Available versions: https://semver.io/node/versions
(Leave blank for default: %s)\\n" "$DEFAULT_NODEJS_VERSION"
read -r -p "> " ASDF_NODEJS_VERSION
export ASDF_NODEJS_VERSION=${ASDF_NODEJS_VERSION:-$DEFAULT_NODEJS_VERSION}

printf "\\nWhich version of Python would you like to install?
(Leave blank for default: %s)\\n" "$DEFAULT_PYTHON_VERSION"
read -r -p "> " ASDF_PYTHON_VERSION
export ASDF_PYTHON_VERSION=${ASDF_PYTHON_VERSION:-$DEFAULT_PYTHON_VERSION}

# Install and configure ASDF
install_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"
install_asdf_plugin "python" 

fancy_echo "Installing Node..."

bash "${HOME}/.asdf/plugins/nodejs/bin/import-release-team-keyring"
install_asdf_language "nodejs" "$ASDF_NODEJS_VERSION"
fancy_echo "Node --> $(command -v node)"
fancy_echo "NPM --> $(command -v npm)"

fancy_echo "Installing Python..."
install_asdf_language "python" "$ASDF_PYTHON_VERSION"

###############################################################################
# Install oh-my-zsh
###############################################################################
fancy_echo "Installing oh-my-zsh..."

if [ ! -d "${HOME}/.oh-my-zsh" ]; then
  git clone https://github.com/robbyrussell/oh-my-zsh.git "${HOME}/.oh-my-zsh"
fi


if [ -d /usr/local/share/zsh ]; then
  fancy_echo "Setting permissions for /usr/local/share/zsh..."
  sudo chmod -R 755 /usr/local/share/zsh
fi

if [ -d /usr/local/share/zsh/site-functions ]; then
  fancy_echo "Setting permissions for /usr/local/share/zsh/site-functions..."
  sudo chmod -R 755 /usr/local/share/zsh/site-functions
fi

if [ ! -d "${ZSH_CUSTOM}/plugins/zsh-autosuggestions" ]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
fi

if [ ! -d "${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting" ]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
fi

if [ ! -d "${ZSH_CUSTOM}/plugins/zsh-history-substring-search" ]; then
  git clone https://github.com/zsh-users/zsh-history-substring-search.git $ZSH_CUSTOM/plugins/zsh-history-substring-search
fi


if [ ! -d "${ZSH_CUSTOM}/plugins/poetry" ]; then
  mkdir -p "${ZSH_CUSTOM}/plugins/poetry"
  poetry completions zsh > $ZSH_CUSTOM/plugins/poetry/_poetry
fi

# add homebrew zsh to allowed shells if it isn't already there
grep -qxF '/usr/local/bin/zsh' /etc/shells || echo '/usr/local/bin/zsh' | sudo tee -a /etc/shells
chsh -s $(which zsh)

# Install yabai scripting additions
if [ ! -f "/private/etc/sudoers.d/yabai" ]; then
  sudo touch /private/etc/sudoers.d/yabai
  echo "$(whoami) ALL = (root) NOPASSWD: $(which yabai) --load-sa" | sudo tee -a /private/etc/sudoers.d/yabai
fi

sudo yabai --install-sa

# Install doom emacs
if [ ! -d "${HOME}/.emacs.d" ]; then
  git clone https://github.com/hlissner/doom-emacs $HOME/.emacs.d
  $HOME/.emacs.d/bin/doom install
fi
