tap 'homebrew/cask'
tap 'aws/tap'
tap 'cigna_techmakers/cignabrew', 'https://git.sys.cigna.com/cigna_techmakers/cignabrew.git'
tap 'mongodb/brew'
tap 'thought-machine/please'

cask 'mattermost'
cask 'figma'
cask 'robo-3t'
cask 'webex'

brew 'certfix'
brew 'awscli'
brew 'yarn'
brew 'aws-sam-cli'
brew 'please'
brew 'mongodb-database-tools'

